//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlowUp
{
    public partial class Cart
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Panel EmptyCartPanel;
        protected global::System.Web.UI.WebControls.Panel CartPanel;
        protected global::System.Web.UI.WebControls.Repeater CartRepeater;
        protected global::System.Web.UI.WebControls.Label TotalLabel;
        protected global::System.Web.UI.WebControls.Button ClearCartButton;
        protected global::System.Web.UI.WebControls.Button CheckoutButton;
    }
}
