//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlowUp
{
    public partial class Checkout
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Panel LoginRequiredPanel;
        protected global::System.Web.UI.WebControls.Panel CheckoutPanel;
        protected global::System.Web.UI.WebControls.Label UserEmailLabel;
        protected global::System.Web.UI.WebControls.Repeater OrderRepeater;
        protected global::System.Web.UI.WebControls.Label OrderTotalLabel;
        protected global::System.Web.UI.WebControls.Button PlaceOrderButton;
        protected global::System.Web.UI.WebControls.Panel SuccessPanel;
    }
}
