//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlowUp
{
    public partial class Product
    {
        protected global::System.Web.UI.WebControls.HyperLink BackLink;
        protected global::System.Web.UI.WebControls.Panel ProductPanel;
        protected global::System.Web.UI.WebControls.Image ProductImage;
        protected global::System.Web.UI.WebControls.Label ProductName;
        protected global::System.Web.UI.WebControls.Label ProductPrice;
        protected global::System.Web.UI.WebControls.Button AddToCartButton;
        protected global::System.Web.UI.WebControls.Panel CartMessagePanel;
        protected global::System.Web.UI.WebControls.Label CartMessage;
        protected global::System.Web.UI.WebControls.Panel NotFoundPanel;
    }
}
